### ISSUE TITLE
Craft 4 Support

### ISSUE THREAD

**Issue by internetztube** [luwes/craft-codemirror#18]
First of all, thank you for this plugin. Now that Craft 4 is about to be released, do you plan to have the plugin ready by then?

**Comment by davidhellmann** [comment]
I'm also interested in this. Any plans here? : )

**Comment by garycrane** [comment]
+1 : Be good to see this in Craft 4 soon.

**Comment by timeverts** [comment]
Yes please!

**Comment by green17** [comment]
Yes please too, great plugin thanks

**Comment by lopugit** [comment]
+1 this, I tried deploying my own package with the craft version simply set to 4 and now I get this error 

```
Fatal error: Declaration of luwes\codemirror\CodeMirror::createSettingsModel() must be compatible with craft\base\Plugin::createSettingsModel(): ?craft\base\Model in /Users/lopu/things/git/thirstcreative/craft4-starter-template-backend/vendor/luwes/craft3-codemirror/src/CodeMirror.php on line 74
```

**Comment by wmdhosting** [comment]
+5 :)

**Comment by richhayler** [comment]
Please bring this to Craft 4

**Comment by richhayler** [comment]
See: https://verbb.io/craft-3

**Comment by bencresty** [comment]
+1 
Great plugin that must continue it's road to Craft 4!

**Comment by engram-design** [comment]
Just to chime in, we've added this to our [Craft 3 migration project](https://verbb.io/craft-3), as people are keen to see this plugin on Craft 4.

If you're no longer developing this plugin, we'd be happy to continue development at Verbb (including updating to Craft 4) - but just let us know if you've got plans to continue things and update to Craft 4! @luwes

**Comment by luwes** [comment]
hey guys, I don't have any plans to migrate or continue maintenance on this plugin.
feel free to take over! cheers

**Comment by davidhellmann** [comment]
💰 sold to verbb! 
congratulations 🤣

But sounds great, thanks!

**Comment by engram-design** [comment]
@luwes Sounds good! If you want to transfer this repository to `verbb` or myself `engram-design` (you might have to add me as a collaborator first, then promote to admin), that'd be great, and we'll get this ported to Craft 4.

**Comment by timeverts** [comment]
Totally amazing news! Thanks Verbb and thanks @luwes for such a useful plugin.

**Comment by farmbureau** [comment]
Thanks in advance, I'm a big fan of this valuable addition to CraftCMS

**Comment by petenice** [comment]
Thanks in advance, I'm a big fan of this helpful field. Looking forward.

**Comment by engram-design** [comment]
@luwes Just wanted to check in about transferring this repo, so we can kick things off?

**Comment by luwes** [comment]
Thanks @khamer and @engram-design!

Sorry for the misunderstanding, I didn't mean to transfer this repo.
I merged @khamer 's PR adding Craft 4 support. thanks for your patience all!

**Comment by engram-design** [comment]
@luwes Works for me, thanks!

**Comment by wmdhosting** [comment]
just checking.... you merged PR for Craft 4 support.. but still not avaible in CRAFT 4 . store to download..
